# Generated by Django 5.2.1 on 2025-05-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='debut_garde',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='fin_garde',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='telephone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_garde', models.DateField()),
                ('fin_garde', models.DateField()),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.pharmacie')),
            ],
        ),
    ]
