# Generated by Django 5.2.1 on 2025-05-08 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_remove_pharmacie_debut_garde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garde',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garde',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
