# Generated by Django 5.2.1 on 2025-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_garde_created_at_garde_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='latitude',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='longitude',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
