# Generated by Django 5.2.1 on 2025-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_pharmacie_latitude_pharmacie_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
